arxiv:
  categories:  # 文章类型
    - cs.CV
    - cs.CL

llm:
  model_name: 'deepseek-chat'  # 使用的LLM模型

wechat:
  api_base_url: 'http://47.117.133.51:30015'  # WeChat API基础URL
  keywords:  # 搜索关键词
    - Agent
    - SWE
    - 强化学习
    - 大模型
